### ISSUE TITLE
咪咕的直播源播放不了

### ISSUE THREAD

**Issue by noob1993129** [Vincentvip/Live#1]
你好：
咪咕的直播源播放不了，能否更新下。谢谢

**Comment by Vincentvip** [comment]
好的.现在更新 大概21点修复.

**Comment by Vincentvip** [comment]
> 你好： 咪咕的直播源播放不了，能否更新下。谢谢

经过测试可以播放的

**Comment by Vincentvip** [comment]
> 你好： 咪咕的直播源播放不了，能否更新下。谢谢

经过测试可以播放，谢谢关注.

**Comment by noob1993129** [comment]
> > 你好： 咪咕的直播源播放不了，能否更新下。谢谢
> 
> 经过测试可以播放，谢谢关注.
HI Vincentvip:  十分感谢你的回复，刚才我尝试了下。咪咕直播无法播放。如果您有时间有新的链接方便的时候更新下，谢谢。
[
![微信图片_20231106193541](https://github.com/Vincentvip/Live/assets/80569194/e1205ba6-d58d-4b80-92e4-5f4954799ea6)
](url)

**Comment by noob1993129** [comment]
Dear @Vincentvip : 
 iOS 中APTV和Windows中 Potplayer 咪咕直播的链接均超时。希望您方便的时候检查更新下。谢谢 ☺
![微信图片_20231106194227](https://github.com/Vincentvip/Live/assets/80569194/d65a58b2-09a5-4265-954d-26efa863c0e0)

**Comment by Vincentvip** [comment]
> 你好： 咪咕的直播源播放不了，能否更新下。谢谢

很高兴收到你的反馈，我这边再次测试过，咪咕ipv6和ipv4都可观看，建议你检查一下本地网络状态。用移动网络测试。谢谢

**Comment by Vincentvip** [comment]
![image](https://github.com/Vincentvip/Live/assets/149390953/f98049f1-66cd-44ff-8ca6-ced2306f8b19)

**Comment by noob1993129** [comment]
Dear @Vincentvip 
我知道原因了，我用移动的流量访问就可以，用家中和公司的wifi访问就不行了。谢谢

**Comment by Vincentvip** [comment]
> 亲爱的@Vincentvip 我知道流量原因了，我用移动的访问就可以了，用家里和公司的wifi访问就不行了。谢谢

请告知我一下你家里和公司使用的是什么地区电信公司，以便我更好处理，因为我只能测试中国移动和中国电信。谢谢

**Comment by noob1993129** [comment]
> > 亲爱的@Vincentvip 我知道流量原因了，我用移动的访问就可以了，用家里和公司的wifi访问就不行了。谢谢
> 
> 请告知我一下你家里和公司使用的是什么地区电信公司，以便我更好处理，因为我只能测试中国移动和中国电信。谢谢

Hi @Vincentvip  使用的天津地区的联通网络。包括WiFi和手机的数据流量不能访问。谢谢！

**Comment by noob1993129** [comment]
Hi  @Vincentvip  :
                              中国电信的网络也无法访问咪咕，机器ping gslbserv.itv.cmvideo.cn，返回超时
![image](https://github.com/Vincentvip/Live/assets/80569194/23a31d69-ae36-4784-b635-73d8148b22ba)

**Comment by Vincentvip** [comment]
> 你好 @Vincentvip : 中国电信的网络也无法访问咪咕，机器ping gslbserv.itv.cmvideo.cn，返回超时 ![图像](https://user-images.githubusercontent.com/80569194/280944153-23a31d69-ae36-4784-b635-73d8148b22ba.png)

收到，明天我会重新整理，希望把移动电信联通分别分组，经过我朋友测试 广州电信可以播放。所以可能是地区原因。
