### ISSUE TITLE
咪咕播放

### ISSUE THREAD

**Issue by fifity2020** [Vincentvip/Live#3]
你好，咪咕cmvideo的节目，我用移动流量、联通宽带都可以播放，但移动家宽就怎么也不行，我是路由器桥接拨号。

**Comment by Vincentvip** [comment]
> 你好，咪咕cmvideo的节目，我用移动流量、联通宽带都可以播放，但移动家宽就怎么也不行，我是路由器桥接拨号。

是否ipv6没有开启

**Comment by fifity2020** [comment]
开了ipv6,所以ipv6的还是没问题的，v4不行。现在我相信运营商做了限制。可能各省情况不同
